// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxpR6TY9qeY-JGZfIlCUE2EaB8M_HkE4s',
    appId: '1:782727628864:ios:933690d23a2c5400bb37a5',
    messagingSenderId: '782727628864',
    projectId: 'recipe-app-flutter2',
    storageBucket: 'recipe-app-flutter2.firebasestorage.app',
    iosBundleId: 'com.example.recipeapp2.recipeApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxpR6TY9qeY-JGZfIlCUE2EaB8M_HkE4s',
    appId: '1:782727628864:ios:933690d23a2c5400bb37a5',
    messagingSenderId: '782727628864',
    projectId: 'recipe-app-flutter2',
    storageBucket: 'recipe-app-flutter2.firebasestorage.app',
    iosBundleId: 'com.example.recipeapp2.recipeApp2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDG-L2lQwZRlKPMpZ4AyQA_HNvO5orOlw',
    appId: '1:782727628864:web:f1c0156ffbc93f59bb37a5',
    messagingSenderId: '782727628864',
    projectId: 'recipe-app-flutter2',
    authDomain: 'recipe-app-flutter2.firebaseapp.com',
    storageBucket: 'recipe-app-flutter2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Vi_ES5K5bg-M9RAOzgRCVkn_rGTotMY',
    appId: '1:782727628864:android:a98867c1caa0360dbb37a5',
    messagingSenderId: '782727628864',
    projectId: 'recipe-app-flutter2',
    storageBucket: 'recipe-app-flutter2.firebasestorage.app',
  );
}
